//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by englishrc.rc
//
#define IDS_HELPFILE					1
#define IDI_APPLICATIONICON             1
#define IDS_LISTNAME                    2
#define IDI_DELETEDFILE                 2
#define IDS_LISTINFOLDER                3
#define IDI_FILE                        3
#define IDC_UP                          3
#define IDS_LISTFULLPATH                4
#define IDI_FILES                       4
#define IDC_SAVE                        4
#define IDS_LISTSHORTFILENAME           5
#define IDC_DOWN                        5
#define IDS_LISTSHORTFILEPATH           6
#define IDC_SHOW                        6
#define IDS_LISTSIZE                    7
#define IDC_DOWN3                       7
#define IDC_HIDE                        7
#define IDS_LISTTYPE                    8
#define IDS_LISTMODIFIED                9
#define IDS_LISTCREATED                 10
#define IDS_LISTACCESSED                11
#define IDS_LISTATTRIBUTES              12
#define IDS_LISTIMAGEINFO               13
#define IDS_LISTOWNER                   14
#define IDS_LISTDATABASE                15
#define IDS_LISTDATABASEDESC            16
#define IDS_LISTDATABASEFILE            17
#define IDS_LISTVOLUMELABEL             18
#define IDS_LISTVOLUMESERIAL            19
#define IDS_LISTVOLUMEFILESYSTEM        20
#define IDS_LISTMD5SUM                  21
#define IDS_LISTAUTHOR                  22
#define IDS_TITLEEXTENSIONS				23
#define IDI_LENS                        23
#define IDS_LOCATINGLIMITREACHED        24
#define IDS_LOCATINGSUCCESS             25
#define IDS_LOCATING                    26
#define IDS_LOCATINGFAILED              27
#define IDS_LOCATINGCANCELLED           28
#define IDS_SEARCHINGFROMFILE           29
#define IDS_NORESULTS                   30
#define IDS_ITEMSFOUND                  31
#define IDS_FILESFOUND                  32
#define IDS_DELETEDFILE                 33
#define IDS_DIRECTORIESFOUND            34
#define IDS_UNKNOWNTYPE                 35
#define IDS_DIRECTORYTYPE               36
#define IDS_TITLE                       37
#define IDS_ALLFILES                    38
#define IDS_TITLESEARCHRESULTS          39
#define IDS_SHORTCUT                    40
#define IDS_SHORTCUTTO                  41
#define IDS_REGULAREXPRESSION           42
#define IDS_REGULAREXPRESSIONFULLPATH   43
#define IDS_DEFAULT                     44
#define IDS_OLDFILE						45
#define IDS_FIRST						46
#define IDS_SECOND						47
#define	IDS_THIRD						48
#define	IDS_NTH							49
#define IDS_BYTES                       50
#define IDS_KB                          51
#define IDS_MB                          52
#define IDS_GB                          53
#define IDS_AM                          54
#define IDS_PM                          55
#define IDS_SYMLINK						56
#define IDS_LISTTITLE                   57
#define IDS_LISTSUBJECT                 58
#define IDS_LISTCATEGORY                59
#define IDS_LISTPAGES                   60
#define IDS_LISTCOMMENTS                61
#define IDS_LISTDESCRIPTION             62
#define IDS_LISTFILEVERSION             63
#define IDS_LISTPRODUCTNAME             64
#define IDS_LISTPRODUCTVERSION          65
#define IDS_LOCATINGWAITDBWRITING       66
#define IDS_JUNCTION					67
#define IDS_SYMLINKDIR					68
#define IDS_LISTEXTENSION				69
#define IDS_HELPINFO                    70
#define IDS_FILEINFORMATION             71
#define IDS_FILEINFORMATIONFMT          72
#define IDS_ERROROCCURED				73
#define IDS_ERROROCCUREDWITHDB			74
#define IDS_LISTKEYWORDS				75
#define IDS_SELECTEDONEFILE				76
#define IDS_SELECTEDONEFOLDER			77
#define IDS_REPLACECHARS				78
#define IDS_REPLACEASTERISKS			79
#define IDS_NAME                        80
#define IDS_ADVANCED                    81
#define IDS_SIZEDATE                    82
#define IDS_DATETODAY					83
#define IDS_REPLACESPACES				84
#define IDS_BYEXTENSION                 85
#define IDS_BUILDINTYPES                86
#define IDS_FILENAMESONLY               87
#define IDS_FILEANDFOLDERNAMES          88
#define IDS_FOLDERNAMESONLY             89
#define IDS_MODIFIED                    90
#define IDS_CREATED                     91
#define IDS_LASTACCESSED                92
#define IDS_SELECTEDCOUNT               93
#define IDS_SELECTEDCOUNT2              94
#define IDS_SELECTEDCOUNT3              95
#define IDS_TOTALSIZE                   96
#define IDS_DATEDAY						97
#define IDS_DATENDAYS					98
#define IDS_COPYRIGHT                   99
#define IDS_REPLACEQMARK				100   
#define IDD_MAIN                        101
#define IDS_YES                         101
#define IDR_MAINMENU                    102
#define IDS_NO                          102
#define IDD_NAME                        103
#define IDS_DOCUMENTFOLDERS             103
#define IDD_ABOUT                       104
#define IDS_GETFOLDER                   104
#define IDC_USEDTHREADLABEL             104
#define IDD_ADVANCED                    105
#define IDC_COMEWITHME                  105
#define IDC_USEDTHREAD                  105
#define IDC_PRESETS                     105
#define IDS_EVERYWERE                   105
#define IDD_DATABASESETTINGS            106
#define IDS_ROOTS                       106
#define IDC_PRESETSLABEL                106
#define IDD_DATABASEINFO                107
#define IDS_LOOKIN                      107
#define IDC_TEXTHELP                    107
#define IDD_ADVANCEDSETTINGS            108
#define IDS_LOOKINCONTRADICTION         109
#define IDD_DBADVANCED					109
#define IDS_NOEXTENSION                 110
#define IDC_COPYRIGHT                   111
#define IDC_YOURRIGHT                   112
#define IDC_YOURRIGHT2                  113
#define IDC_SYSINFO                     115
#define IDS_OK                          116
#define IDS_CANCEL                      117
#define IDR_POPUPMENU                   120
#define IDI_LANIM1                      168
#define IDI_LANIM2                      169
#define IDI_LANIM3                      170
#define IDI_LANIM4                      171
#define IDI_LANIM5                      172
#define IDI_LANIM6                      173
#define IDR_SYSTEMTRAYMENU              190
#define IDI_UANIM1                      191
#define IDI_UANIM2                      192
#define IDD_AUTOUPDATESETTINGS          192
#define IDI_UANIM3                      193
#define IDD_SCHEDULEDUPDATE             193
#define IDI_UANIM4                      194
#define IDI_UANIM5                      195
#define IDI_UANIM6                      196
#define IDI_UANIM7                      197
#define IDI_UANIM8                      198
#define IDI_UANIM9                      199
#define IDI_UANIM10                     200
#define IDI_UANIM11                     201
#define IDI_UANIM12                     202
#define IDI_UANIM13                     203
#define IDI_YES                         204
#define IDI_NO                          205
#define IDD_RESULTSAVEDIALOG2000        206
#define IDD_RESULTSAVEDIALOGFRAMES      207
#define IDS_REMOVEFROMTHISLIST          210
#define IDS_OPENCONTAININGFOLDER        211
#define IDS_OPEN                        212
#define IDS_STRING21                    213
#define IDS_SELECTDETAILS               213
#define IDR_SEARCHFROMFILE              222
#define IDR_LOCATEHELP                  223
#define IDR_UPDATEDBHELP                224
#define IDD_INPUTBOX                    225
#define IDM_SELECTDETAILS               227
#define IDD_SELECTDETAILS               229
#define IDD_DATABASEDIALOG              230
#define IDD_SELECTDATABASES             231
#define IDD_CHANGECASE                  232
#define IDD_CHANGEFILENAME              233
#define IDD_PRESETNAME                  234
#define IDD_PRESETREMOVE                235
#define IDD_DELETEPRIVATEDATA           236
#define IDD_SAVERESULTSPROGRESS			237
#define IDS_UPDATINGDATABASE            300
#define IDS_UPDATINGDATABASE2           301
#define IDS_UPDATINGWRITINGDATABASE     302
#define IDS_UPDATINGSUCCESS             303
#define IDS_UPDATINGFAILED              304
#define IDS_UPDATINGCANCELLED           305
#define IDS_UPDATINGCANCELLED2          306
#define IDS_UPDATINGDONE                307
#define IDS_UPDATINGUNAVAILABLEROOT     308
#define IDS_UPDATINGTOOLTIPTITLE        309
#define IDS_UPDATINGFAILED2             310
#define IDS_UPDATINGUPDATING            311
#define IDS_UPDATINGSCANNINGROOT        312
#define IDS_UPDATINGDELAYWRITING		313
#define IDS_UPDATINGCONFIRMATION		314
#define IDS_PRIORITYHIGH                390
#define IDS_PRIORITYABOVENORMAL         391
#define IDS_PRIORITYNORMAL              392
#define IDS_PRIORITYBELOWNORMAL         393
#define IDS_PRIORITYLOW                 394
#define IDS_PRIORITYIDLE                395
#define IDS_PRIORITYBACKGROUND          396
#define IDS_NOTIFYLOCATEWITHNAMED       399
#define IDS_NOTIFYLOCATE                400
#define IDS_NOTIFYUPDATING              401
#define IDS_NOTIFYUPDATINGDBS           402
#define IDS_NOTIFYUPDATINGDBS2          403
#define IDS_NOTIFYTHREAD                404
#define IDS_NOTIFYDONE                  405
#define IDS_NOTIFYWRITINGDATABASE       406
#define IDS_NOTIFYINITIALIZING          407
#define IDS_UPDATINGTHREAD              408
#define IDS_UPDATINGENDED               409
#define IDS_NOTIFYFINISHING             410
#define IDS_TOOLTIPFORFILE              500
#define IDS_TOOLTIPFORDIRECTORY         501
#define IDS_TOOLTIPFORFILEDELETED       502
#define IDS_TOOLTIPFORDIRECTORYDELETED  503
#define IDS_TOOLTIPDESCRIPTION          504
#define IDS_TOOLTIPTARGET               505
#define IDS_TOOLTIPAUTHOR               506
#define IDS_TOOLTIPTITLE		        507
#define IDS_TOOLTIPCOMMENTS             508
#define IDS_TOOLTIPFILEVERSION	        509
#define IDS_TOOLTIPPRODUCTVERSION       510
#define IDC_NAMESTATIC                  601
#define IDC_TYPESTATIC                  602
#define IDC_LOOKINSTATIC                603
#define IDC_CHECKSTATIC                 604
#define IDC_FILETYPESTATIC              605
#define IDC_NEXT                        606
#define IDC_PREV                        607
#define IDC_SWAPWITHPREVIOUS            608
#define IDC_SWAPWITHNEXT                609
#define IDC_OK                          1000
#define IDS_ERROR                       1000
#define IDC_CANCEL                      1001
#define IDC_STOP                        1001
#define IDS_ERRORCANNOTOPENDB           1001
#define IDC_EDIT                        1002
#define IDC_NEWSEARCH                   1002
#define IDS_ERRORCANNOTREADDB			1002
#define IDC_TEXT                        1003
#define IDS_ERRORCANNOTALLOCATE         1003
#define IDC_TAB                         1004
#define IDS_SHORTCUTTODESKTOP           1004
#define IDS_ERRORINVALIDFILEFORMAT      1005
#define IDC_FILELIST                    1006
#define IDC_NAMELABEL                   1006
#define IDC_STATUS                      1007
#define IDS_ERRCANNOTFIND               1007
#define IDC_NAME                        1008
#define IDS_ERRORCANNOTCREATE           1008
#define IDS_ERRORCANNOTRENAME           1009
#define IDC_MOREDIRECTORIES             1009
#define IDC_LOOKIN                      1010
#define IDS_ERRORCANNOTOPENDBFORWRITE   1010
#define IDC_BROWSE                      1011
#define IDS_ERRORCANNOTOPENDBFORREAD	1011
#define IDC_FRAME                       1012
#define IDS_CANNOTREADDRIVE             1012
#define IDC_UPDATENOW                   1012
#define IDC_TYPE                        1013
#define IDC_FRAME2                      1013
#define IDS_ERRORNODRIVES               1013
#define IDC_NOSUBDIRECTORIES            1014
#define IDC_FRAME3                      1014
#define IDS_ERRORCANNOTREADDBWITHOSERROR 1014
#define IDC_FILEICON                    1015
#define IDS_ERRORUNKNOWN                1015
#define IDC_FILENAME                    1016
#define IDS_ERRORINVALIDDB              1016
#define IDC_FILETYPE                    1017
#define IDS_ERRORCANNOTWRITEDB          1017
#define IDC_FILELOCATION                1018
#define IDS_ERRORCANNOTWRITEDBWITHOSERROR 1018
#define IDC_FILESIZE                    1019
#define IDS_ERRORWRONGDRIVE2            1019
#define IDS_ERRORNOCOLUMNSSELECTED      1019
#define IDC_MSDOSNAME                   1020
#define IDC_FILES                       1020
#define IDS_ERRORNOCOLUMNSSELECTED2     1020
#define IDS_ERRORCANNOTADDITEM          1020
#define IDS_ERRORCANNOTADDITEM2         1021
#define IDC_CREATED                     1021
#define IDC_MODIFIED                    1022
#define IDS_ERRORCNODATABASESSELECTED   1022
#define IDS_ERRORDIRECTORYNOTFOUND      1023
#define IDC_READONLY                    1024
#define IDS_ERRORROOTNOTAVAILABLE       1024
#define IDS_ERRORUNKNOWNOS              1025
#define IDC_HIDDEN                      1025
#define IDS_ERRORUNKNOWNWRITEDB         1026
#define IDC_ARCHIVE                     1026
#define IDC_HIDDEN2                     1026
#define IDS_ERRORUNKNOWNSCANROOT        1027
#define IDC_SYSTEM                      1027
#define IDS_ERRORCANNOTWRITEINCREMENTALLY 1028
#define IDC_COMPRESSED                  1028
#define IDS_ERRORCANNOTSAVESHORTCUTS    1029
#define IDC_TARGET                      1030
#define IDS_ERRORCANNOTLOADDEFAULTSHORTUCS 1030
#define IDC_TARGETLOCATION              1031
#define IDS_ERRORDIFFERENTCHARSETINDB   1031
#define IDS_ERRORJUNCTIONS				1032
#define IDC_TARGETTYPE                  1032
#define IDC_STARTIN                     1033
#define IDS_ERRORROOTNOTAVAILABLEASKREMOVE 1033
#define IDS_ERRORCANNOTCREATETHREAD     1034
#define IDC_RUNMODE                     1035
#define IDS_ERRORCOUNINITIALIZE			1035
#define IDC_FINDTARGET                  1036
#define IDC_SHORTCUTKEY                 1038
#define IDC_DATABASEFILEICON            1039
#define IDC_DBFILELABEL                 1041
#define IDC_PROPSHEET                   1042
#define IDC_USEDDATABASE                1043
#define IDC_DBFILE                      1044
#define IDC_LOCALDRIVES                 1048
#define IDC_CUSTOMDRIVES                1049
#define IDC_SYSTEMSETTINGS              1049
#define IDC_NEXTCONTROL                 1050
#define IDC_POINTTOSELECT               1050
#define IDC_PREVCONTROL                 1051
#define IDC_USE                         1052
#define IDC_FILE                        1053
#define IDC_NEXTTAB                     1054
#define IDC_PREVTAB                     1055
#define IDC_WRITEINI                    1056
#define IDC_CREATORLABEL                1056
#define IDC_CREATOR                     1057
#define IDC_POINTUNDERLINE              1057
#define IDC_DESCRIPTION                 1058
#define IDC_DESCRIPTIONLABEL            1059
#define IDC_VERSION                     1059
#define IDC_DIRECTORIES                 1060
#define IDC_ALWAYSUNDERLINE             1061
#define IDC_DIRECTORYNAMES              1061
#define IDC_CHARSET                     1062
#define IDC_CHECKMINIMUMSIZE            1062
#define IDC_CHECKMAXIMUMSIZE            1063
#define IDC_MINIMUMSIZE                 1064
#define IDC_MAXIMUMSIZE                 1065
#define IDC_MAXIMUMSIZESPIN             1066
#define IDC_MINIMUMSIZESPIN             1067
#define IDC_CHECKMINDATE                1068
#define IDC_CHECKMAXDATE                1069
#define IDC_MINDATE                     1070
#define IDC_MAXDATE                     1071
#define IDC_MINTYPE                     1072
#define IDC_MAILME                      1073
#define IDC_MAXTYPE                     1073
#define IDC_GOTOHOMEPAGE                1074
#define IDC_MINSIZETYPE                 1074
#define IDC_MAXSIZETYPE                 1075
#define IDC_DONATE						1075
#define IDC_MINDATEMODE                 1076
#define IDC_MAXDATEMODE                 1077
#define IDC_UPDATES                     1079
#define IDC_ADD                         1080
#define IDC_DELETE                      1082
#define IDC_ENABLED                     1084
#define IDC_TIME                        1085
#define IDC_EVERY                       1086
#define IDC_EVERYSPIN                   1087
#define IDC_EVERYTXT                    1088
#define IDC_DAYS                        1089
#define IDC_WEEKS                       1090
#define IDC_ADDACTION                   1090
#define IDC_MON                         1091
#define IDC_REMOVEACTION                1091
#define IDC_WED                         1092
#define IDC_TUE                         1093
#define IDC_THU                         1094
#define IDC_FRI                         1095
#define IDC_SAT                         1096
#define IDC_SUN                         1097
#define IDC_MDAY                        1098
#define IDC_MTHE                        1099
#define IDC_MEVERY                      1100
#define IDS_QUITNOW                     1100
#define IDC_MSPIN                       1101
#define IDS_QUITNOW2                    1101
#define IDC_OFTHEMONTHS                 1102
#define IDC_ONCETIME                    1103
#define IDC_MTYPE                       1104
#define IDC_MDAYS                       1105
#define IDC_OFTHEMONTHS2                1106
#define IDC_RUNON                       1107
#define IDC_DELETEAFTERRUN              1108
#define IDC_SUMMARY                     1109
#define IDC_LASTRUN                     1109
#define IDC_TITLE                       1110
#define IDC_UPDATEWHENPOSSIBLE          1110
#define IDC_TITLE2                      1111
#define IDC_DATE                        1111
#define IDC_HOURS                       1112
#define IDC_SHELLTITLE                  1112
#define IDC_MINUTESPIN                  1113
#define IDC_OWNTITLE                    1113
#define IDC_MINUTEONHOUR                1114
#define IDC_1STCHARUPPER                1114
#define IDC_MINUTEONHOURLBL             1115
#define IDC_ALWAYSSHOWEXTENSIONS        1115
#define IDC_HIDEEXTENSIONSFORKNOWN      1116
#define IDC_MINUTE                      1117
#define IDC_NEVERSHOWEXTENSIONS         1117
#define IDC_SHOWICONS                   1118
#define IDC_HELPTOOLBAR                 1118
#define IDC_SHOWFILETYPE                1119
#define IDC_ACTIONTOOLBAR               1119
#define IDC_SHOWFILETIME                1120
#define IDC_MAXIMUMFOUNDFILES           1121
#define IDC_ASCENDINGORDER              1122
#define IDC_DESCENDINGORDER             1123
#define IDC_OWNTYPE                     1124
#define IDC_SHELLTYPE                   1125
#define IDC_FOLDERSLABEL                1125
#define IDC_FOLDERS                     1126
#define IDC_ADDFOLDER                   1127
#define IDC_REMOVEFOLDER                1128
#define IDC_MATCHWHOLENAME              1129
#define IDC_ADVANCED					1130
#define IDC_DATEFORMAT                  1131
#define IDC_TIMEFORMAT                  1132
#define IDC_CHECK                       1132
#define IDC_CONTAINDATACHECK            1133
#define IDC_CONTAINDATA                 1134
#define IDC_DATAMATCHCASE               1135
#define IDC_DIRECTORYNAME               1136
#define IDC_CLOSEBUTTONMINIMIZESWINDOW  1137
#define IDC_EXCLUDEFILES                1137
#define IDC_INCLUDEFILES                1138
#define IDC_MINIMIZETOSYSTEMTRAY        1139
#define IDC_INCLUDEDIRECTORIES          1139
#define IDC_REMEMBERSTATES              1140
#define IDC_CLOSETOSYSTEMTRAY           1141
#define IDC_LOCATEONMYCOMPUTER          1142
#define IDC_SORTING                     1143
#define IDC_SORTINGLABEL				1144
#define IDC_MATCHWHOLEFILENAMEONLY      1145
#define IDC_REPLACESPACES               1146
#define IDC_CHECKIN                     1147
#define IDC_MATCHCASE                   1148
#define IDC_LANGUAGE                    1148
#define IDC_USEWITHCONSOLEAPPS          1149
#define IDC_CHECKINLABEL				1149
#define IDC_STATICWHEN                  1150
#define IDC_IMAGE                       1150
#define IDC_ABOUTBANNER                 1150
#define IDC_COLUMNS                     1151
#define IDC_THREADS                     1152
#define IDC_WIDTH                       1152
#define IDC_WIDTHSPIN                   1153
#define IDC_THREADSPIN                  1153
#define IDC_DBINFO                      1154
#define IDC_WHEN                        1154
#define IDC_DETAILS                     1155
#define IDC_LIST                        1156
#define IDC_LABELS                      1157
#define IDC_USEWHOLEPATH                1158
#define IDC_TOOLBAR                     1159
#define IDC_ALLITEMS                    1160
#define IDC_SELECTEDITEMS               1161
#define IDC_DESCRIPTIONTOGGLE           1162
#define IDC_ENABLE                      1162
#define IDC_EXTENSIONS                  1162
#define IDC_GLOBALUPDATE                1163
#define IDC_DATABASES                   1163
#define IDC_RESTORE                     1164
#define IDC_DISABLE                     1165
#define IDC_NEW                         1166
#define IDC_REMOVE                      1167
#define IDC_UPDATE                      1168
#define IDC_RESET                       1168
#define IDC_UPDATE2                     1169
#define IDC_OVERRIDETXT                 1169
#define IDC_RESETACTIONS                1170
#define IDS_SCANSYMLINKSANDJUNCTIONS	1171
#define IDC_STOPIFROOTUNAVAILABLE       1172
#define IDC_THREADSLABEL                1172
#define IDC_SENTENCECASE                1173
#define IDC_TITLECASE                   1174
#define IDC_TOGGLECASE                  1175
#define IDC_TREE1                       1175
#define IDC_LOWERCASE                   1176
#define IDC_KEYLIST                     1176
#define IDC_UPPERCASE                   1177
#define IDC_SHORTCUT                    1177
#define IDC_EXCLUDEONLYCONTENT			1178
#define IDC_ACTION                      1179
#define IDC_ACTION2                     1181
#define IDC_SUBACTION                   1181
#define IDC_TEMPLATE                    1182
#define IDC_ENCODING					1185
#define IDC_FROMMNEMONIC                1184
#define IDC_ENCODING					1185
#define IDC_WAITDELAY                   1186
#define IDC_WAITPOST                    1187
#define IDC_WAITMS                      1188
#define IDC_WAITNONE                    1189
#define IDC_WINDOWCLASS                 1190
#define IDC_WINDOWTITLE                 1191
#define IDC_CHECK1                      1192
#define IDC_LOCATEDIALOG                1192
#define IDC_MODSHIFT                    1192
#define IDC_SPACE                       1192
#define IDC_EXECUTEWHENKEYISDOWN        1193
#define IDC_MODALT                      1193
#define IDC_HYPHEN                      1193
#define IDC_REMOVEDOWNMESSAGE           1194
#define IDC_MODCTRL                     1194
#define IDC_UNDERLINE                   1194
#define IDC_EXECUTEWHENKEYISUP          1195
#define IDC_MODWIN                      1195
#define IDC_REMOVEUPMESSAGE             1196
#define IDC_EXECUTEWHENSTATIC           1197
#define IDC_QUESTIONMARK                1197
#define IDC_REMOVEMESSAGESTATIC         1198
#define IDC_RADIO1                      1199
#define IDC_SENDKEYRELEASEBEFOREWIN		1199
#define IDC_RIGHT                       1199
#define IDC_SELECTALLKEY                1200
#define IDC_LEFT                        1200
#define IDC_CODE                        1200
#define IDC_CENTER                      1201
#define IDC_FILESANDDIRECTORIES         1201
#define IDC_IMPORT                      1202
#define IDC_ALIGN                       1202
#define IDC_STATICWHEREPRESSED          1202
#define IDC_TYPES                       1202
#define IDC_CUSTOM                      1202
#define IDC_EXPORT                      1203
#define IDC_STATICCLASS                 1203
#define IDC_INCREMENTALUPDATE           1204
#define IDC_STATICWINDOWTITLE           1204
#define IDC_TYPES2                      1204
#define IDC_UNICODE                     1205
#define IDC_STATICEXECUTAIONOPTIONS     1205
#define IDC_SIZEOFILES                  1205
#define IDC_STATICWAITBEFOREEXECUTE     1206
#define IDC_SIZEONDISK                  1206
#define IDC_VKISSCANCODE                1207
#define IDC_STATICWHENPRESSED           1208
#define IDD_RESULTSAVEDIALOG            1209
#define IDC_WHENPRESSED                 1209
#define IDC_WHEREPRESSED                1209
#define IDD_RESULTPRINTDIALOG           1210
#define IDD_GENERALSETTINGS             1211
#define IDD_SIZEDATE                    1212
#define IDD_LANGUAGESETTINGS            1213
#define IDD_KEYBOARDSHORTCUTS           1214
#define IDD_SHORTCUTADVANCED            1215
#define IDC_STATICACTIONS               1216
#define IDD_FILEPROPERTIES              1216
#define IDC_STATICACTION                1217
#define IDD_REPLACECHARS                1217
#define IDC_STATICSUBACTION             1218
#define IDC_STATICSHORTCUT              1219
#define IDC_HOTKEYRADIO                 1220
#define IDC_CODERADIO                   1221
#define IDC_STATICVERB                  1222
#define IDC_VERB                        1223
#define IDC_STATICWINDOW                1224
#define IDC_WINDOW                      1225
#define IDC_STATICMESSAGE               1226
#define IDC_MESSAGE                     1227
#define IDC_STATICWPARAM                1228
#define IDC_WPARAM                      1229
#define IDC_STATICLPARAM                1230
#define IDC_LPARAM                      1231
#define IDC_STATICCOMMAND               1232
#define IDC_COMMAND                     1233
#define IDC_THREADPRIORITY              1234
#define IDC_THREADPRIORITYLABEL         1235
#define IDC_STATICWHICHFILE             1236
#define IDC_WHICHFILE                   1237
#define IDC_STATICVALUE                 1238
#define IDC_VALUE                       1239
#define IDC_VALUEHELPTEXT               1240
#define IDC_CPUUSAGECHECK               1241
#define IDC_CPUUSAGESPIN                1242
#define IDC_DELAYSPIN					1242
#define IDC_CPUUSAGE                    1243
#define IDC_DELAY						1243
#define IDC_CPUUSAGEEXTRALABEL          1244
#define IDC_SET							1245
#define IDC_PATHINDATABASE				1246
#define IDC_PATHINDATABASELABEL			1247
#define IDC_STATICITEM                  1248
#define IDC_ITEM                        1249
#define IDC_ITEMSPIN                    1250
#define IDC_USEDATABASESLABEL			1251
#define IDC_USEDATABASESTEMPORALLY      1252
#define IDC_USEDATABASESONCE            1253
#define IDC_STATICCONTEXTMENUFOR        1254
#define IDC_CONTEXTMENUFOR              1255
#define IDC_FORMATTEXT					1256
#define IDC_FORMATHTML					1257
#define IDC_FINDTEXT					1300
#define IDC_FINDNEXT					1301
#define IDC_SEARCHUP					1302
#define IDC_SEARCHDOWN					1303
#define IDC_CLEARNAMED					1400
#define IDC_CLEAREXTENSTIONS			1401
#define IDC_CLEARLOOKIN					1402
#define IDC_PROGRESS					1403
#define IDS_LASTERROR                   1900
#define IDS_LASTERRORUNKNOWN            1901
#define IDS_LASTERRORINVALIDDB          1902
#define IDS_LASTERRORROOTUNAVAILABLE    1903
#define IDS_LASTERRORCANNOTINCREMENTDB  1904
#define IDS_LASTERRORCANNOTALLOCATE     1905
#define IDS_LASTERRORCANNOTOPEN         1906
#define IDS_LASTERRORCANNOTREAD         1907
#define IDS_LASTERRORCANNOTWRITE        1908
#define IDS_LASTERRORUNKNOWN2           1909
#define IDS_SIZEMB                      2007
#define IDS_SIZEKB                      2008
#define IDS_SIZEBYTES                   2009
#define IDS_ALLOFTYPE                   2017
#define IDS_ALLIN                       2018
#define IDS_DATABASEINFOCAPTION         2030
#define IDS_DBVERSION1                  2031
#define IDS_DBVERSION2                  2032
#define IDS_DBVERSIONSFN                2033
#define IDS_DBVERSIONLFN                2034
#define IDS_DBVERSIONNEW                2035
#define IDS_OEMCHARSET                  2036
#define IDS_ANSICHARSET                 2037
#define IDS_UNICODECHARSET              2038
#define IDI_DATABASEFILEICON            2039
#define IDS_VOLUMETYPE                  2040
#define IDS_VOLUMEPATH                  2041
#define IDS_VOLUMELABEL                 2042
#define IDS_VOLUMESERIAL                2043
#define IDS_VOLUMEFILESYSTEM            2044
#define IDS_VOLUMEFILES                 2045
#define IDS_VOLUMEDIRECTORIES           2046
#define IDS_VOLUMEINDATABASE			2047
#define IDS_VOLUMETYPEUNKNOWN           2050
#define IDS_VOLUMETYPEFIXED             2051
#define IDS_VOLUMETYPEREMOVABLE         2052
#define IDS_VOLUMETYPECDROM             2053
#define IDS_VOLUMETYPEREMOTE            2054
#define IDS_VOLUMETYPERAMDISK           2055
#define IDS_VOLUMETYPEDIRECTORY         2056
#define IDS_VOLUMETYPEDIRECTORY2        2057
#define IDS_VOLUMETYPECOMPUTER          2057
#define IDS_INVALIDCHARACTERS			2099
#define IDS_CANNOTEXCLUDESELECTED       2100
#define IDS_ALREADYEXCLUDED             2101
#define IDS_NEWMAP						2102
#define IDS_CLKFORNEWMAP				2103
#define IDS_ENTERNEWDIRECTORY			2104
#define IDS_EMPTY                       3000
#define IDS_NONE                        3001
#define IDS_UNKNOWN                     3002
#define IDS_AND							3003
#define IDS_NOTE						3004
#define IDS_NOSORTNG                    3999
#define IDS_CHANGEICON                  4000
#define IDS_IMPORTDATABASEFILTERS       4001
#define IDS_EXPORTDATABASEFILTERS       4002
#define IDS_PROGRAMSFILTERS				4003
#define IDS_SAVERESULTSFILTERS          4004
#define IDS_ICONFILTERS					4005
#define IDS_SAVERESULTS                 4010
#define IDS_SAVERESULTSHEADER           4011
#define IDS_SAVERESULTSDATE             4012
#define IDS_SAVERESULTSDBCAPTION        4013
#define IDS_SAVERESULTSDB               4014
#define IDS_INCREASETHREADCOUNT         4015
#define IDS_UNABLEREADSETTINGS          4016
#define IDS_FILEISNOTDATABASE           4017
#define IDS_CANNOTWRITESETTINGS         4018
#define IDS_SAVERESULTSDBNAME           4019
#define IDS_SAVERESULTSDBCREATOR        4020
#define IDS_SAVERESULTSDBDESCRIPTION    4021
#define IDS_SAVERESULTSDBFILE           4022
#define IDS_SAVERESULTSTITLE            4023
#define IDS_SAVERESULTSTITLE2           4024
#define IDS_SAVERESULTSANSI				4025
#define IDS_SAVERESULTSUNICODE			4026
#define IDS_SAVERESULTSUTF8				4027
#define IDS_SAVERESULTSINVALIDFORMAT	4028
#define IDS_SAVERESULTSCANNOTSAVERESULTS 4029
#define IDS_SAVERESULTSNOTEMPLATE		4030
#define IDS_SETTINGS                    5000
#define IDS_GENERALSETTINGS             5001
#define IDS_DATABASESETTINGS            5002
#define IDS_AUTOUPDATESETTINGS          5003
#define IDS_ADVANCEDSETTINGS            5004
#define IDS_LANGUAGESETTINGS            5005
#define IDS_SHORTCUTSETTINGS            5006
#define IDS_NONEPARENTHESIS				5130
#define IDS_MONDAY                      5131
#define IDS_TUESDAY                     5132
#define IDS_WEDNESDAY                   5133
#define IDS_THURSDAY                    5134
#define IDS_FRIDAY                      5135
#define IDS_SATURDAY                    5136
#define IDS_SUNDAY                      5137
#define IDS_MON                         5138
#define IDS_TUE                         5139
#define IDS_WED                         5140
#define IDS_THU                         5141
#define IDS_FRI                         5142
#define IDS_SAT                         5143
#define IDS_SUN                         5144
#define IDS_LASTTIMEUPDATED             5200
#define IDS_DATABASENAME                5201
#define IDS_DATABASEFILE                5202
#define IDS_GLOBALUPDATE                5203
#define IDS_THREADID                    5204
#define IDS_THREADNAME                  5205
#define IDS_DATABASECREATOR             5206
#define IDS_DATABASEDESCRIPTION         5207
#define IDS_DELETEDATABASE              5208
#define IDS_DELETEDATABASEQUESTION      5209
#define IDS_REMOVABLESTRING                5210
#define IDS_CDROMSTRING                 5211
#define IDS_DATABASEFILTERS             5212
#define IDS_SELECTDATABASE              5213
#define IDS_NOTEXIST                    5214
#define IDS_FOLDEREXIST                 5215
#define IDS_SUBFOLDER                   5216
#define IDS_ADDFOLDER                   5217
#define IDS_IMPORTDATABASESETTINGS      5218
#define IDS_EXPORTDATABASESETTINGS      5219
#define IDS_NAMEALREADYEXISTS           5220
#define IDS_FILEALREADYEXISTS           5221
#define IDS_INVALIDFILENAME             5222
#define IDS_INVALIDDBNAME               5223
#define IDS_DBNOTVALID                  5224
#define IDS_NAMEISRESERVED              5225
#define IDS_COMMANDLINEARGUMENT         5226
#define IDS_INVALIDFILENAMEISOK         5227
#define IDS_LANGUAGE                    5301
#define IDS_LANGUAGEFILE                5302
#define IDS_LANGUAGEDESC                5303
#define IDS_LANGUAGEVERSION             5304
#define IDS_LANGUAGENOTE                5305
#define IDS_ADVSETDIALOGS               5401
#define IDS_ADVSETLOADTYPES             5402
#define IDS_ADVSETNUMBEROFDIRECTORIES   5403
#define IDS_ADVSETDONTADDANYROOTS       5404
#define IDS_ADVSETADDSELECTEDROOTS      5405
#define IDS_ADVSETADDALLROOTS           5406
#define IDS_ADVSETMULTIPLEDIRECTORIES   5407
#define IDS_ADVSETLOOKINCOMBO           5408
#define IDS_ADVSETLARGEMODEONLY         5409
#define IDS_ADVSETLOCATEPROCESS         5410
#define IDS_ADVSETSHOWDATESINFORMAT     5411
#define IDS_ADVSETSHOWTIMESINFORMAT     5412
#define IDS_ADVSETRESULTSLIST			5413
#define IDS_ADVSETUPDATERESULTS         5414
#define IDS_ADVSETDISABLEUPDATING       5415
#define IDS_ADVSETENABLEUPDATING        5416
#define IDS_ADVSETDISABLEFSCHANGETRACKING 5417
#define IDS_ADVSETENABLEFSCHANGETRACKING 5418
#define IDS_ADVSETENABLEFSCHANGETRACKINGOLD 5419
#define IDS_ADVSETLIMITRESULTS          5421
#define IDS_ADVSETCHANGE                5422
#define IDS_ADVSETMAXNUMBEROFRESULTS    5423
#define IDS_ADVSETSYSTEMDEFAULT         5424
#define IDS_ADVSETUPDATEPROCESS         5425
#define IDS_ADVSETSHOWCRITICALERRORS    5426
#define IDS_ADVSETSHOWNONCRITICALERRORS 5427
#define IDS_ADVSETSHOWUPDATESTATUSTOOLTIP 5428
#define IDS_ADVSETCOMPUTEMD5SUMS        5429
#define IDS_ADVSETSHELLCONTEXTMENU      5430
#define IDS_ADVSETLOCATEINMYCOMPUTER    5431
#define IDS_ADVSETLOCATEINMYDOCUMENTS   5432
#define IDS_ADVSETLOCATEINDRIVES        5433
#define IDS_ADVSETLOCATEINFOLFERS       5434
#define IDS_ADVSETUPDATEINMYCOMPUTER    5435
#define IDS_ADVSETTOPMOST               5436
#define IDS_ADVSETSHOWFILESIZESINFORMAT 5437
#define IDS_ADVSETFORMATWITHUSERLOCALE  5438
#define IDS_ADVSETUPDATETHREADPRIORITY  5439
#define IDS_ADVSETSYSTEM                5440
#define IDS_ADVSETNODELAYEDUPDATING     5441
#define IDS_ADVSETRUNATSYSTEMSTARTUP    5442
#define IDS_ADVSETTRANSPARENCY          5443
#define IDS_ADVSETTOOLTIPTEXTCOLOR      5444
#define IDS_ADVSETTOOLTIPTITLECOLOR     5445
#define IDS_ADVSETTOOLTIPERRORCOLOR     5446
#define IDS_ADVSETTOOLTIPBACKCOLOR      5447
#define IDS_ADVSETTOOLTIPTITLEFONT      5448
#define IDS_ADVSETTOOLTIPTEXTFONT       5449
#define IDS_ADVSETTOOLTIPTRANSPARENCY   5450
#define IDS_ADVSETUSEGETTITLE           5451
#define IDS_ADVSETUSEOWNMETHODFORTITLE  5452
#define IDS_ADVSETUSESIMPLEICONS        5453
#define IDS_ADVSETSHOWFILETYPES         5454
#define IDS_ADVSETUSESHELLFORTYPE       5455
#define IDS_ADVSETUSEOWNMETHODFORTYPE   5456
#define IDS_ADVSETFIRSTCHARUPPER        5457
#define IDS_ADVSETALWAYSSHOWEXT         5458
#define IDS_ADVSETHIDEEXTFORKNOWN       5459
#define IDS_ADVSETNEVERSHOWEXT          5460
#define IDS_ADVSETMISCELLANEOUS         5461
#define IDS_ADVSETDONTSHOWHIDDENFILES   5462
#define IDS_ADVSETUSEPROGRAMFORFOLDERS  5463
#define IDS_ADVSETOPENFOLDERWITH        5464
#define IDS_ADVSETSHOWTOOLTIPS			5465
#define IDS_ADVSETNODOUBLERESULTS       5466
#define IDS_ADVSETFILESIZEFORMATLESS1KB 5467
#define IDS_ADVSETFILESIZEFORMATDEPENGINGSIZE 5468
#define IDS_ADVSETFILESIZEFORMATBYTES   5469
#define IDS_ADVSETFILESIZEFORMATBYTENOUNITS 5470
#define IDS_ADVSETFILESIZEFORMATKB      5471
#define IDS_ADVSETFILESIZEFORMATKBNOUNITS 5472
#define IDS_ADVSETFILESIZEFORMATMB      5473
#define IDS_ADVSETFILESIZEFORMATMBNOUNITS 5474
#define IDS_ADVSETFOLDERSFIRST          5475
#define IDS_ADVSETSETTOOLTIPDELAYS      5476
#define IDS_ADVSETSHOWTOOLTIPDELAY      5477
#define IDS_ADVSETSHOWTOOLTIPDURATION   5478
#define IDS_ADVSETACTIVATEFIRSTITEM     5479
#define IDS_ADVSETUSECUSTOMFONTINRESULTLIST 5480
#define IDS_ADVSETRESULTLISTFONT        5481
#define IDS_ADVSETDONTSHOWEXTINRENAME   5482
#define IDS_ADVSETTOOLTIPALWAYSONTOP    5483
#define IDS_ADVSETTOOLTIPTOPIFFOREGROUNDNOTMAXIMIZED 5484
#define IDS_ADVSETTOOLTIPTOPIFFOREGROUNDNOTFULLSCREEN 5485
#define IDS_ADVSETTOOLTIPNEVERONTOP     5486
#define IDS_ADVSETNUMBEROFNAMES         5487
#define IDS_ADVSETNUMBEROFTYPES         5488
#define IDS_ADVSETTOOLTIPWINDOWPOSITION 5489
#define IDS_ADVSETTOOLTIPPOSNEARCLOCK   5490
#define IDS_ADVSETTOOLTIPPOSUPPERLEFT   5491
#define IDS_ADVSETTOOLTIPPOSUPPERRIGHT  5492
#define IDS_ADVSETTOOLTIPPOSLOWERLEFT   5493
#define IDS_ADVSETTOOLTIPPOSLOWERRIGHT  5494
#define IDS_ADVSETTOOLTIPWINDOWONTOP    5495
#define IDS_ADVSETTOOLTIPPOSLASTPOSITION 5496
#define IDS_ADVSETFULLROWSELECT         5497
#define IDS_ADVSETFILESIZEFORMATLESS1MB 5498
#define IDS_ADVSETCLICKACTIVATETRAYICON	5499 // Will continue at 5800
#define IDS_SHORTCUTADDACTION           5506
#define IDS_SHORTCUTREMOVEACTION        5507
#define IDS_SHORTCUTNEXTACTION          5508
#define IDS_SHORTCUTPREVACTION          5509
#define IDS_SHORTCUTSWAPWITHPREVIOUS    5510
#define IDS_SHORTCUTSWAPWITHNEXT        5511
#define IDS_SHORTCUTACTION              5512
#define IDS_SHORTCUTACTION2             5513
#define IDS_SHORTCUTLISTLABELSHORTCUT   5514
#define IDS_SHORTCUTLISTLABELTYPE       5515
#define IDS_SHORTCUTLISTLABELACTION     5516
#define IDS_SHORTCUTMULTIPLEACTIONS     5517
#define IDS_SHORTCUTNONE                5518
#define IDS_SHORTCUTMODEXT              5519
#define IDS_SHORTCUTMODCTRL             5520
#define IDS_SHORTCUTMODALT              5521
#define IDS_SHORTCUTMODSHIFT            5522
#define IDS_SHORTCUTSCANCODE            5523
#define IDS_SHORTCUTWHENFOCUSINRESULTLIST 5524
#define IDS_SHORTCUTWHENNAMETABSHOWN    5525
#define IDS_SHORTCUTWHENSIZEDATETABSHOWN 5526
#define IDS_SHORTCUTWHENADVANCEDTABSHOWN 5527
#define IDS_SHORTCUTWHENFOCUSNOTINRESULTLIST 5528
#define IDS_SHORTCUTSUBACTION           5529
#define IDS_SHORTCUTSUBACTIONCONTROL    5530
#define IDS_SHORTCUTSUBACTIONTAB        5531
#define IDS_SHORTCUTSUBACTIONMENUITEM   5532
#define IDS_SHORTCUTSUBACTIONPRESET     5533
#define IDS_SHORTCUTWHENIFISRUNNING		5534
#define IDS_SHORTCUTWHENIFISNOTRUNNING	5535
#define IDS_KEYCONTAINDATA              5554
#define IDS_SHORTCUTMENUFILENOITEM      5560
#define IDS_SHORTCUTMENUFILEITEM        5561
#define IDS_SHORTCUTMENUEDIT            5562
#define IDS_SHORTCUTMENUVIEW            5563
#define IDS_SHORTCUTMENUVIEWARRANGEICONS 5564
#define IDS_SHORTCUTMENUTOOLS         5565
#define IDS_SHORTCUTMENUHELP            5566
#define IDS_SHORTCUTMENUSPECIAL         5567
#define IDS_SHORTCUTMENUPRESETS         5568
#define IDS_SHORTCUTMENUDIRECTORIES     5569
#define IDS_ADVSHORTCUTLOCAL            5571
#define IDS_ADVSHORTCUTGLOBALHOTKEY     5572
#define IDS_ADVSHORTCUTGLOBALHOOK       5573
#define IDS_KEYMAXDATEMODE				5583
#define IDS_KEYMINDATEMODE				5584
#define IDS_KEYMAXDATEVALUE             5585
#define IDS_KEYMINDATEVALUE             5586
#define IDS_KEYMAXSIZEVALUE             5587
#define IDS_KEYMINSIZEVALUE             5588
#define IDS_KEYMAXDATETYPE              5589
#define IDS_KEYRESULTLIST               5590
#define IDS_KEYMOREDIRECTORIES          5591
#define IDS_KEYTEXTHELPBUTTON           5592
#define IDS_KEYNEXTCONTROL              5593
#define IDS_KEYPREVCONTROL              5594
#define IDS_KEYNEXTTAB                  5595
#define IDS_KEYPREVTAB                  5596
#define IDS_KEYMINSIZETYPE              5597
#define IDS_KEYMAXSIZETYPE              5598
#define IDS_KEYMINDATETYPE              5599
#define IDS_KEYNUM0                     5600
#define IDS_KEYNUM1                     5601
#define IDS_KEYNUM2                     5602
#define IDS_KEYNUM3                     5603
#define IDS_KEYNUM4                     5604
#define IDS_KEYNUM5                     5605
#define IDS_KEYNUM6                     5606
#define IDS_KEYNUM7                     5607
#define IDS_KEYNUM8                     5608
#define IDS_KEYNUM9                     5609
#define IDS_KEYBACKSPACE                5610
#define IDS_KEYTAB                      5611
#define IDS_KEYENTER                    5612
#define IDS_KEYESC                      5613
#define IDS_KEYSPACE                    5614
#define IDS_KEYPAGEUP                   5615
#define IDS_KEYPAGEDOWN                 5616
#define IDS_KEYEND                      5617
#define IDS_KEYHOME                     5618
#define IDS_KEYLEFT                     5619
#define IDS_KEYUP                       5620
#define IDS_KEYRIGHT                    5621
#define IDS_KEYDOWN                     5622
#define IDS_KEYPRINTSCREEN              5623
#define IDS_KEYINS                      5624
#define IDS_KEYDEL                      5625
#define IDS_KEYNUMADD                   5626
#define IDS_KEYNUMSUB                   5627
#define IDS_KEYNUMMUL                   5628
#define IDS_KEYNUMDIV                   5629
#define IDS_KEYNUMDECIMAL               5630
#define IDS_KEYSCROLLLOCK               5631
#define IDS_KEYPAUSE                    5632
#define IDS_KEYCAPSLOCK                 5633
#define IDS_KEYNUMLOCK                  5634
#define IDS_KEYF1                       5635
#define IDS_KEYF2                       5636
#define IDS_KEYF3                       5637
#define IDS_KEYF4                       5638
#define IDS_KEYF5                       5639
#define IDS_KEYF6                       5640
#define IDS_KEYF7                       5641
#define IDS_KEYF8                       5642
#define IDS_KEYF9                       5643
#define IDS_KEYF10                      5644
#define IDS_KEYF11                      5645
#define IDS_KEYF12                      5646
#define IDS_KEYF13                      5647
#define IDS_KEYF14                      5648
#define IDS_ACTIONCATSETTINGS			5699
#define IDS_ACTIONCATHELP	            5700
#define IDS_ACTIONCATACTIVATECONTROL    5701
#define IDS_ACTIONCATACTIVATETAB        5702
#define IDS_ACTIONCATMENUCOMMAND        5703
#define IDS_ACTIONCATSHOWHIDEDIALOG     5704
#define IDS_ACTIONCATTRESULTLIST        5705
#define IDS_ACTIONCATMISC               5707
#define IDS_ACTIONCATCHANGEVALUE        5708
#define IDS_ACTIONCATPRESETS            5709
#define IDS_ACTIONSWDIALOGSHOW          5710
#define IDS_ACTIONSWDIALOGMINIMINZE     5711
#define IDS_ACTIONSWDIALOGCLOSE         5712
#define IDS_ACTIONSWDIALOGSHOWORHIDE    5713
#define IDS_ACTIONSWDIALOGOPENORCLOSE   5714
#define IDS_ACTIONSWDIALOGRESTORE       5715
#define IDS_ACTIONSWDIALOGMAXIMIZE      5716
#define IDS_ACTIONSWDIALOGMAXIMIZEORRESTORE 5717
#define IDS_ACTIONSWDIALOGSHOWOPENORHIDE 5718
#define IDS_ACTIONSWDIALOGSHOWANDDIRFROMEXPLORER 5719
#define IDS_ACTIONRESITEMEXECUTE        5720
#define IDS_ACTIONRESITEMCOPY           5721
#define IDS_ACTIONRESITEMCUT            5722
#define IDS_ACTIONRESITEMRECYCLE        5723
#define IDS_ACTIONRESITEMDELETE         5724
#define IDS_ACTIONRESITEMOPENCONTEXTMENU 5725
#define IDS_ACTIONRESITEMOPENCONTEXTMENUSIMPLE 5726
#define IDS_ACTIONRESITEMOPENFOLDER     5727
#define IDS_ACTIONRESITEMOPENCONTFOLDER 5728
#define IDS_ACTIONRESITEMPROPERTIES     5729
#define IDS_ACTIONRESITEMSPECIALMENU    5730
#define IDS_ACTIONRESITEMEXECUTECOMMAND 5731
#define IDS_ACTIONRESITEMSELECTFILE     5732
#define IDS_ACTIONRESITEMNEXTFILE       5733
#define IDS_ACTIONRESITEMPREVFILE       5734
#define IDS_ACTIONRESITEMNEXTNONDELETEDFILE 5735
#define IDS_ACTIONRESITEMPREVNONDELETEDFILE 5736
#define IDS_ACTIONRESITEMRENAMEFILE		5737
#define IDS_ACTIONSWDIALOGSSTOPLOCATINGORCLOSEDIALOG 5738
#define IDS_ACTIONADVSENDMESSAGE        5740
#define IDS_ACTIONADVPOSTMESSAGE        5741
#define IDS_ACTIONRESITEMSELECTNTHITEM	5742
#define IDS_ACTIONRESITEMEXECUTENTHITEM	5743
#define	IDS_ACTIONADVINSERTASTERISKS	5744
#define IDS_ACTIONHELPSHOW				5750
#define IDS_ACTIONHELPCLOSE				5751
#define IDS_ACTIONHELPTOPICS			5752
#define IDS_ACTIONHELPINDEX				5753
#define IDS_ACTIONHELPTOC				5754
#define IDS_ACTIONHELPSEARCH			5755
#define IDS_ACTIONOPENSETTINGSTAB		5756
#define IDS_ACTIONCONTEXTMENUFORFILE	5757
#define IDS_ACTIONCONTEXTMENUFORPARENT	5758
#define IDS_ADVSETCUSTOMTRAYICON		5800
#define IDS_ADVSETICONFILE				5801
#define IDS_ADVSETSELECTICONFILE		5802
#define IDS_ADVSETSELECTPROGRAM			5803
#define IDS_ADVSETALLOWINPLACERENAMING  5804
#define IDS_ADVSETDONTSHOWDELETEDFILES  5805
#define IDS_ADVSETUSEDEFDIRECTORYICON	5806
#define IDS_ADVSETDONTSAVENETWORKDRIVES 5807
#define IDS_ADVSETWHILESORTINGDONOTREADINFO	5808
#define IDS_ADVSETDONTRESOLVEDRIVEICONS	5809
#define	IDS_ADVSETDONTSAVELISTITEMS		5810
#define	IDS_ADVSETLOGICALOPERATIONS		5811
#define	IDS_ADVSETSPACEISSEPARATOR		5812
#define IDS_ADVSETDONTSHOWSTICON		5813
#define IDS_ADVSETSYSTEMTRAYICON		5814
#define IDS_ADVSETISENABLE				5815
#define IDS_ADVSETISLIMIT				5816
#define IDS_ADVSETISNAMEDCHANGED		5817
#define IDS_ADVSETISTYPECHANGED			5818
#define IDS_ADVSETISLOOKINCHANGED		5819
#define IDS_ADVSETISSIZESCHANGED		5820
#define IDS_ADVSETISDATESCHANGED		5821
#define IDS_ADVSETISDATACHANGED			5822
#define IDS_ADVSETISOTHERCHANGED		5823
#define IDS_ADVSETISDISABLEIFDATASEARCH	5824
#define IDS_ADVSETISDELAY				5825
#define IDS_ADVSETISUPDOWNGORESULTS		5826
#define	IDS_ADVSETMATCHWHOLENAMEIFASTERISKS	5827
#define IDS_ADVSETISCHARS				5828
#define IDS_ADVSETHEADERINALLVIEWMODES  5829
#define IDS_ADVSETICONSNOFILEACCESS		5830
#define IDS_ADVSETCUSTOMDIALOGICON		5831
#define IDS_ADVSETNOASTERISKATENDIFEXTENSIONGIVEN 5832
#define IDS_ADVSETCONFIRMATIONFORUPDATEDATABASES 5833
#define IDS_ADVSETVIEWMODES				5834
#define IDS_ADVSETTHUMBSWITHMEDIUMICONS 5835
#define IDS_ADVSETLARGEICONSIZE			5836
#define IDS_ADVSETEXTRALARGEICONSIZE	5837
#define IDS_ADVSETANDMODEALWAYS			5838
#define IDS_ADVSETISBYCOMMANDLINE		5839
#define IDS_ADVSETSIMPLEFILEMENU		5840
#define IDS_ADVSETSORTINGMETHOD			5841
#define IDS_ADVSETSORTINGSTANDARD		5842
#define IDS_ADVSETSORTINGSTANDARDCS		5843
#define IDS_ADVSETSORTINGNATURAL		5844
#define IDS_ADVSETSORTINGNATURALCS		5845
#define IDS_ADVSETCANNOTFINDOPTION		5846
#define IDS_ADVSETDONTMOVETOOLTIPS		5847
#define IDS_ADVSETEXECUTEMODE			5848
#define IDS_ADVSETEXECUTEMODEDEFAULT	5849
#define IDS_ADVSETEXECUTEMODECONTEXT	5850
#define IDS_ADVSETENABLEADDREFFIX		5851
#define IDS_ADVSETISUPDATETITLE			5852
#define IDS_SCHEDULEUPDATE              5901
#define IDS_MINUTELY                    5909
#define IDS_HOURLY                      5910
#define IDS_DAILY                       5911
#define IDS_WEEKLY                      5912
#define IDS_MONTHLY                     5913
#define IDS_ONCE                        5914
#define IDS_ATSTARTUP                   5915
#define IDS_WEEKFIRST                   5921
#define IDS_WEEKSECOND                  5922
#define IDS_WEEKTHIRD                   5923
#define IDS_WEEKFOURTH                  5924
#define IDS_WEEKLAST                    5925
#define IDS_RESULTSTRING                6000
#define IDS_PRESETSAVETITLE             6100
#define IDS_OVERWRITEPRESET             6101
#define IDS_PRESETNAMENOTVALID          6102
#define IDS_PRESETGLOBAL                6103
#define IDS_PRESETLATEST                6104
#define IDS_PRESETPARAM                 6105
#define IDS_PRESETSELECTED              6106
#define IDS_PRESETCUSTOM                6107
#define IDS_CHANGEFILENAMEALREADYEXISTS 6200
#define IDS_DAILYEVERYDAY               7000
#define IDS_DAILYEVERYXDAYS             7001
#define IDS_WEEKLYEVERYWEEK             7002
#define IDS_WEEKLYEVERYXWEEKS           7003
#define IDS_MONTHLYEVERYDAY             7004
#define IDS_MONTHLYEVERYTYPE            7005
#define IDS_ATTIMEON                    7006
#define IDS_ATSTARTUPSTR                7007
#define IDS_HOURLYLYEVERYXHOUR          7008
#define IDS_HOURLYLYEVERYHOUR           7009
#define IDS_MINUTELYEVERYMINUTE         7010
#define IDS_MINUTELYEVERYXMINUTE        7011
#define IDS_LASTRUN                     7100
#define IDS_LASTRUNNEVER                7101
#define IDS_DETAILLEFTCLICK             7300
#define IDS_DETAILLEFTDBLCLICK          7301
#define IDS_DETAILRIGHTCLICK            7302
#define IDS_DETAILRIGHTDBLCLICK         7303
#define IDS_DETAILMIDDLECLICK           7304
#define IDS_DETAILMIDDLEDLBCLICK        7305
#define IDS_EXPLORERLOCATE              8000
#define IDS_EXPLORERUPDATE              8001
#define IDS_FILEPROPERTIESPAGETITLE     9000
#define IDS_FILEPROPERTIESSHEETCAPTION	9001
#define IDS_FILEPROPERTIESPAGEMULTIPLETYPES	9002
#define IDS_FILEPROPERTIESPAGEFILESFMT		9003
#define IDS_FILEPROPERTIESPAGESIZEFMT		9004
#define IDS_FILEPROPERTIESALLOFTYPE		9005
#define IDC_NEVERUNDERLINE              11024
#define IDC_CLICKTOSELECT               11025
#define IDC_ICONS                       12297
#define IDS_SYSWIN32S                   27001
#define IDS_SYSWIN95                    27002
#define IDS_SYSWIN98                    27003
#define IDS_SYSWINNT                    27004
#define IDS_SYSWINME                    27006
#define IDS_SYSWIN2000WORKSTATION       27007
#define IDS_SYSWIN2000SERVER            27008
#define IDS_SYSWIN2000ENTEPRISE         27009
#define IDS_SYSWINXP                    27010
#define IDS_SYSWIN2003SERVER            27011
#define IDS_SYSWINVISTA		            27012
#define IDS_SYSWINSERVERLONGHORN		27013
#define IDS_SYSWIN7			            27014
#define IDS_SYSPAGEDMEM                 27030
#define IDS_SYSPHYSMEM                  27031
#define IDS_VERSION                     27032
#define IDS_UPDATEDB32DIRECTORYISNOTVALID 30002
#define IDS_UPDATEDB32CANNOTCREATEFILE  30005
#define IDS_UPDATEDB32CANNOTWRITE       30006
#define IDS_UPDATEDB32ALLOCATEMEM       30008
#define IDS_UPDATEDB32UNKOWNERROR       30009
#define IDS_UPDATEDB32UPDATINGDATABASE  30010
#define IDS_UPDATEDB32UPDATINGDATABASE2 30011
#define IDS_UPDATEDB32SCANNING          30012
#define IDS_UPDATEDB32WRITINGDB         30013
#define IDS_UPDATEDB32CANNOTCHANGELOADED 30014
#define IDS_UPDATEDB32ROOTUNAVAILABLE   30015
#define IDS_UPDATEDB32CANNOTUPDATEINCREMENTALLY 30016
#define IDS_UPDATEDB32INCREMENTALUPDATE 30017
#define IDS_UPDATEDB32USINGEXISTINGSETTINGS 30018
#define IDS_UPDATEDB32WRONGCHARSETINDB  30019
#define IDS_LOCATEFILENOTFOUND          31001
#define IDS_LOCATESTRING                31002
#define IDS_LOCATEUNKNOWNERROR          31003
#define IDS_LOCATECANNOTOPEN            31004
#define IDS_LOCATECANNOTREAD            31005
#define IDS_LOCATEINVALIDDATABASE       31006
#define IDS_LOCATEVERBOSESTR            31007
#define IDS_LOCATEVERBOSEEXT            31008
#define IDS_LOCATEVERBOSEDIR            31009
#define IDS_LOCATEVERBOSEREG            31010
#define IDS_LOCATEVERBOSEFOUNDFILES     31011
#define IDS_EXTLOCATEMENU               32001
#define IDM_CLOSE                       40001
#define IDM_CREATESHORTCUT              40002
#define IDM_DELETE                      40003
#define IDM_RENAME                      40004
#define IDM_OPENCONTAININGFOLDER        40005
#define IDM_PROPERTIES                  40007
#define IDM_ABOUT                       40008
#define IDM_LOOKINNEWSELECTION          40009
#define IDM_LOOKINREMOVESELECTION       40010
#define IDM_LARGEICONS                  40011
#define IDM_SMALLICONS                  40012
#define IDM_LIST                        40013
#define IDM_DETAILS                     40014
#define IDM_ARRANGENAME                 40015
#define IDM_ARRANGEFOLDER               40016
#define IDM_ARRANGETYPE                 40017
#define IDM_ARRANGESIZE                 40018
#define IDM_ARRANGEDATE                 40019
#define IDM_AUTOARRANGE                 40020
#define IDM_LOOKINNEXTSELECTION         40021
#define IDM_CUT							40022
#define IDM_LOOKINPREVSELECTION			40023
#define IDM_EDIT_SELECTALL              40024
#define IDM_COPY						40025
#define IDM_EDIT_INVERTSELECTION        40026
#define IDM_PRESETSAVE                  40027
#define IDM_PRESETREMOVE                40028
#define IDM_ARRANGEEXTENSION            40029
#define IDM_EXTRALARGEICONS             40030
#define IDM_MEDIUMICONS                 40031
#define IDM_SETTINGS                    40033
#define IDM_SETTOOL						40034
#define IDM_DATABASEINFO                40035
#define IDM_DELETEPRIVATEDATA			40036
#define IDM_PASTE						40037
#define IDM_SAVERESULT                  40038
#define IDM_HELPTOPICS					40039
#define IDM_EXIT                        40040
#define IDM_OPENLOCATE                  40041
#define IDM_GLOBALUPDATEDB              40042
#define IDM_UPDATEDATABASES             40043
#define IDM_FINDUSINGDBS                40046
#define IDM_STOPUPDATING                40048
#define IDM_SHOWINGROUPS                40050
#define IDM_ALIGNTOGRID                 40051
#define IDM_REFRESH                     40052
#define IDM_LINEUPICONS                 40053
#define IDM_EMPTY                       40055
#define IDC_RETURN                      40056
#define IDM_REMOVEFROMTHISLIST          40059
#define IDM_COMPUTEMD5SUM               40060
#define IDM_MD5SUMSFORSAMESIZEFILES     40061
#define IDM_DEFOPEN                     40062
#define IDM_COPYPATHTOCB                40063
#define IDM_CHANGEFILENAME              40064
#define IDM_COPYMD5SUMTOCLIPBOARD       40065
#define IDM_CHANGECASE                  40066
#define IDM_COPYSHORTPATHTOCB           40067
#define IDM_FORCEUPDATE                 40068
#define IDM_UPDATEDATABASESOFSELECTEDFILES 40069
#define IDM_COPYDATATOCB				40070
#define IDM_SHOWFILEINFORMATION         40073
#define IDM_REMOVEDELETEDFILES          40074
#define IDM_EXPLICITDATE				40075
#define IDM_RELATIVEDATE				40077
#define IDM_DEFSHORTCUTITEM             49000
#define IDM_DEFMENUITEM                 50000
#define IDM_DEFCONTEXTITEM              51000
#define IDM_DEFSENDTOITEM               52000
#define IDM_DEFUPDATEDBITEM             54000



#define IDC_HELPBUTTON					32651


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        236
#define _APS_NEXT_COMMAND_VALUE         40063
#define _APS_NEXT_CONTROL_VALUE         1202
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
