////////////////////////////////////////////////////////////////////
// HFC Library - Copyright (C) 1999-2010 Janne Huttunen
////////////////////////////////////////////////////////////////////
//						COM/OLE Implementation
////////////////////////////////////////////////////////////////////

#include "HFCLib.h"
#include "HFCCom.h"


#ifdef DEF_COM

// CCoUnknown implementaion

COMSTD_CONSTRUCTORIMPLEMENTATION(CCoUnknown)

COMSTD_DESTRUCTORIMPLEMENTATION(CCoUnknown)

COMSTD_REFIMPLEMENTATION(CCoUnknown)

COMSTD_QUERYINTERFACEIMPLEMENTATIONBEGIN(CCoUnknown)
COMSTD_QUERYHANDLEINTERFACE(IID_IUnknown)
COMSTD_QUERYINTERFACEIMPLEMENTATIONEND

// CCoDropSource
COMSTD_CONSTRUCTORIMPLEMENTATION(CCoDropSource)

COMSTD_DESTRUCTORIMPLEMENTATION(CCoDropSource)

COMSTD_REFIMPLEMENTATION(CCoDropSource)

COMSTD_QUERYINTERFACEIMPLEMENTATIONBEGIN(CCoDropSource)
COMSTD_QUERYHANDLEINTERFACE(IID_IUnknown)
COMSTD_QUERYHANDLEINTERFACE(IID_IDropSource)
COMSTD_QUERYINTERFACEIMPLEMENTATIONEND

// CCoDropTarget
COMSTD_CONSTRUCTORIMPLEMENTATION(CCoDropTarget)

COMSTD_DESTRUCTORIMPLEMENTATION(CCoDropTarget)

COMSTD_REFIMPLEMENTATION(CCoDropTarget)

COMSTD_QUERYINTERFACEIMPLEMENTATIONBEGIN(CCoDropTarget)
COMSTD_QUERYHANDLEINTERFACE(IID_IUnknown)
COMSTD_QUERYHANDLEINTERFACE(IID_IDropTarget)
COMSTD_QUERYINTERFACEIMPLEMENTATIONEND

// CCoDataObject
COMSTD_CONSTRUCTORIMPLEMENTATION(CCoDataObject)

COMSTD_DESTRUCTORIMPLEMENTATION(CCoDataObject)

COMSTD_REFIMPLEMENTATION(CCoDataObject)

COMSTD_QUERYINTERFACEIMPLEMENTATIONBEGIN(CCoDataObject)
COMSTD_QUERYHANDLEINTERFACE(IID_IUnknown)
COMSTD_QUERYHANDLEINTERFACE(IID_IDataObject)
COMSTD_QUERYINTERFACEIMPLEMENTATIONEND

// CCoEnumFORMATETC
COMSTD_CONSTRUCTORIMPLEMENTATION(CCoEnumFORMATETC)

COMSTD_DESTRUCTORIMPLEMENTATION(CCoEnumFORMATETC)

COMSTD_REFIMPLEMENTATION(CCoEnumFORMATETC)

COMSTD_QUERYINTERFACEIMPLEMENTATIONBEGIN(CCoEnumFORMATETC)
COMSTD_QUERYHANDLEINTERFACE(IID_IUnknown)
COMSTD_QUERYHANDLEINTERFACE(IID_IEnumFORMATETC)
COMSTD_QUERYINTERFACEIMPLEMENTATIONEND


#endif